{"uuid": "ada1040b-8d34-4e94-97db-6f439447a5e3", "children": ["0e1a831f-ed5c-4c1a-882d-8d4578be6425"], "befores": [{"name": "driver", "status": "passed", "start": 1697351584055, "stop": 1697351585189}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=62557): Max retries exceeded with url: /session/b88fae698e1147e7e9438d2641d196ee/window/maximize (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1066e4350>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/nugrahpratama/Developer/selenium/test.py\", line 40, in driver\n    driver.maximize_window()\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 496, in maximize_window\n    self.execute(command, None)\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 342, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 297, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 318, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 118, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 217, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 874, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 844, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/nugrahpratama/Developer/test/venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1697351595517, "stop": 1697351595602}], "start": 1697351584055, "stop": 1697351595603}