[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1066e63d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b88fae698e1147e7e9438d2641d196ee/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1066e6cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b88fae698e1147e7e9438d2641d196ee/window/maximize
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1066e7a50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b88fae698e1147e7e9438d2641d196ee/window/maximize